### ISSUE TITLE
Add support for Jasmine

### ISSUE THREAD

**Issue by jzaefferer** [jquery/testswarm#167]
At this point, the two JS testing frameworks that seem to get the most attention are QUnit and Jasmine. TestSwarm shouldn't really care about which one you use, so adding support for Jasmine seems like a good idea. Might be enough to just add a check and hooks for it in the main integration script.

Even if not a priority for the jQuery project, maybe someone already implemented it - we're certainly interested in adding support.

**Comment by Krinkle** [comment]
This is now working per https://github.com/jquery/testswarm/commit/d8114f8fbe0fddd0d92fd4e32231565af9638914.

| Screenshots
|--
| <img width="716" alt="screen shot 2017-08-07 at 21 28 30" src="https://user-images.githubusercontent.com/156867/29056622-26d3669a-7bb9-11e7-9cfe-90bc3b5ef07b.png">
| <img width="528" alt="screen shot 2017-08-07 at 21 28 41" src="https://user-images.githubusercontent.com/156867/29056619-24d5f63c-7bb9-11e7-91b0-2ead9fa2a7bb.png">
