### ISSUE TITLE
How to test private repositories?

### ISSUE THREAD

**Issue by jzaefferer** [jquery/testswarm#194]
In order to make TestSwarm work with BrowserStack integration interesting to more projects, we need to have a story for testing private repositories. BrowserStack supports the local tunnel for manual testing, but afaik not for API workers. Is there a solution for that? Should we ask BrowserStack about it?

**Comment by Krinkle** [comment]
Closing given this is resolved per @geekdave, and I've seen this work elsewhere as well.
