### ISSUE TITLE
Automate setup

### ISSUE THREAD

**Issue by patrickkettner** [jquery/testswarm#239]
As discussed in #238, it would be great to ease the setup of new installations of testswarm. 

what tasks should be covered by this?
- initialize submodule
- create config files

**Comment by Krinkle** [comment]
As of #280, we're now using [Composer](https://getcomposer.org/) for dependencies. This makes installation a bit easier and more familiar for those working with other PHP applications. It also enjoys an existing corpus of good tutorials and documentation on how to get started.
