### ISSUE TITLE
Support dataURI as run url

### ISSUE THREAD

**Issue by dlai0001** [jquery/testswarm#263]
I'm looking to support passing in dataURI into test swarm.  This will allow me to skip having a webserver to serve up the unit tests.

DataURI would look something like,

[data:text/html;base64,Cgo8aHRtbD4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5RVW5pdCBFeGFtcGxlPC90aXRsZT4KICA8IS0tIFF1bml0IHN0dWZmIC0tPgogIDxsaW5rIHJlbD0ic3R5bGVzaGVldCIgaHJlZj0iaHR0cDovL2NvZGUuanF1ZXJ5LmNvbS9xdW5pdC9xdW5pdC1naXQuY3NzIj4KICA8c2NyaXB0IHNyYz0iaHR0cDovL2NvZGUuanF1ZXJ5LmNvbS9xdW5pdC9xdW5pdC1naXQuanMiPjwvc2NyaXB0PgogIAogIDwhLS0gdGVzdCBzd2FybSBsaW5rIC0tPgogIDxzY3JpcHQgc3JjPSJodHRwOi8vbXl0ZXN0c3dhcm0uaW50ZXJuYWwuY29tL2pzL2luamVjdC5qcyI+PC9zY3JpcHQ+CgogIDwhLS0gYXBwbGljYXRpb24gc2NyaXB0cyAtLT4KPHNjcmlwdD4KeCA9IDE7Cjwvc2NyaXB0PgoKICA8IS0tIFRlc3RzIC0tPgogIDxzY3JpcHQ+CnRlc3QoICJoZWxsbyB0ZXN0IiwgZnVuY3Rpb24oKSB7CiAgb2soIHggPT0gIjEiLCAiUGFzc2VkISIgKTsKfSk7CgogIAogIDwvc2NyaXB0PgoKPC9oZWFkPgo8Ym9keT4KICA8ZGl2IGlkPSJxdW5pdCI+PC9kaXY+CiAgPGRpdiBpZD0icXVuaXQtZml4dHVyZSI+PC9kaXY+CiAgPC9ib2R5Pgo8L2h0bWw+Cg==](data:text/html;base64,Cgo8aHRtbD4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5RVW5pdCBFeGFtcGxlPC90aXRsZT4KICA8IS0tIFF1bml0IHN0dWZmIC0tPgogIDxsaW5rIHJlbD0ic3R5bGVzaGVldCIgaHJlZj0iaHR0cDovL2NvZGUuanF1ZXJ5LmNvbS9xdW5pdC9xdW5pdC1naXQuY3NzIj4KICA8c2NyaXB0IHNyYz0iaHR0cDovL2NvZGUuanF1ZXJ5LmNvbS9xdW5pdC9xdW5pdC1naXQuanMiPjwvc2NyaXB0PgogIAogIDwhLS0gdGVzdCBzd2FybSBsaW5rIC0tPgogIDxzY3JpcHQgc3JjPSJodHRwOi8vbXl0ZXN0c3dhcm0uaW50ZXJuYWwuY29tL2pzL2luamVjdC5qcyI+PC9zY3JpcHQ+CgogIDwhLS0gYXBwbGljYXRpb24gc2NyaXB0cyAtLT4KPHNjcmlwdD4KeCA9IDE7Cjwvc2NyaXB0PgoKICA8IS0tIFRlc3RzIC0tPgogIDxzY3JpcHQ+CnRlc3QoICJoZWxsbyB0ZXN0IiwgZnVuY3Rpb24oKSB7CiAgb2soIHggPT0gIjEiLCAiUGFzc2VkISIgKTsKfSk7CgogIAogIDwvc2NyaXB0PgoKPC9oZWFkPgo8Ym9keT4KICA8ZGl2IGlkPSJxdW5pdCI+PC9kaXY+CiAgPGRpdiBpZD0icXVuaXQtZml4dHVyZSI+PC9kaXY+CiAgPC9ib2R5Pgo8L2h0bWw+Cg==)

However, test swarm appends get prameters to the end of the URL, which causes the data URI to break.  I'm looking for a workaround, or some way to modify the injection to be able to handle data URIs.

**Comment by Krinkle** [comment]
Declining new feature development.
