### ISSUE TITLE
Use actual frames instead of iframes

### ISSUE THREAD

**Issue by jzaefferer** [jquery/testswarm#285]
busterjs uses a frameset, containing one invisible (height 0) control frame and one main frame that contains the page under test (what currently is loaded in an iframe).

This might be something worth trying within TestSwarm, to avoid the issues we have with the iframe, without changing too much at once.

**Comment by Krinkle** [comment]
Closing for now per https://github.com/jquery/testswarm/issues/195#issuecomment-139715857
