### ISSUE TITLE
Edge 14 seems to get stucks 25% of the time

### ISSUE THREAD

**Issue by workmanw** [jquery/testswarm#312]
We've been noticing more and more that Edge 14 seems to be getting "stuck" when running tests. (FWIW we're using browserstack via [testswarm-browserstack](https://github.com/clarkbox/testswarm-browserstack)). After a bit of debugging, I'm seeing this happen on about 25% of the Edge 14 runs:

``` json
"Edge": {
  "data": {
    "browserFamily": "Edge",
    "browserMajor": "14",
    "browserMinor": "",
    "browserPatch": "",
    "osFamily": "",
    "osMajor": "",
    "osMinor": "",
    "osPatch": "",
    "deviceFamily": "",
    "deviceMajor": "",
    "deviceMinor": "",
    "displayInfo": {
      "class": "swarm-icon swarm-browser swarm-browser-edge swarm-browser-edge-14",
      "title": "Edge 14",
      "labelText": "Edge 14",
      "labelHtml": "Edge 14"
    }
  },
  "stats": {
    "onlineClients": 1,
    "activeRuns": 0,
    "pendingRuns": 1,
    "pendingReRuns": 0
  }
}
```

For whatever reason we have an `onlineClient` and a `pendingRuns`, but it's just sitting there not executing the job. I'm curious if anyone else has seen this problem?

EDIT: Also worth noting that when I watch the automated runs, I can see that all the tests pass, the runner goes into "cooling down mode", then cycles back to what looks like "polling mode". But it didn't report the successful test run, and it doesn't seem to pick up the test for a rerun.

Maybe the runner knows it just ran that specific test? IDK. But it definitely seems like when it gets into this funk state, it's like it failed to report the successful run back to testswarm.

**Comment by mgol** [comment]
We're seeing the same in jQuery Core tests: http://swarm.jquery.org/project/jquery. Note that on Edge 13 they mostly pass.

**Comment by workmanw** [comment]
@mgol Man that's good to know. I thought I was going crazy. I have some cycles I can dedicate to this, but I don't really know where to begin. Do you have any thoughts?

**Comment by jcook793** [comment]
@workmanw you still could be crazy

**Comment by Krinkle** [comment]
Closing for now. I believe the issue was a combination of Edge 14's user-agent being slightly off, ua-parser not detecting it as such, browserstack running a point-version of it, and [testswarm-browserstack](https://github.com/clarkbox/testswarm-browserstack) not mapping it.

Not much we could've done, and given it seems to have resolved it self, closing this issue for now.

**Comment by workmanw** [comment]
I'm not sure I agree with that assessment, but it's not a big deal.
