### ISSUE TITLE
Error: SwarmException: MySQL functions missing. in /var/www/html/testswarm/inc/Database.php:325

### ISSUE THREAD

**Issue by ssomu015** [jquery/testswarm#318]
Hi ,

I trying to configure "testswarm" on Ubuntu 16.04.6 LTS, but getting below error while executing the install.php. kindly help me on this. Thanks. 

PHP Version : PHP 7.0.33-0ubuntu0.16.04.2
Mysql Version : Server version: 5.7.25-0ubuntu0.16.04.2 (Ubuntu)
Apache2 Version : Server version: Apache/2.4.18 (Ubuntu

php scripts/install.php

[TestSwarm 1.0.0-alpha] Maintenance script

DBInstall: Install the TestSwarm database. Can also clear a database if it exists.
           ------------------------------------------------------------------------

Error: SwarmException: MySQL functions missing. in /var/www/html/testswarm/inc/Database.php:325
Stack trace:
#0 /var/www/html/testswarm/inc/Database.php(330): Database->checkEnvironment()
#1 /var/www/html/testswarm/inc/Database.php(35): Database->__construct()
#2 /var/www/html/testswarm/inc/TestSwarm.php(55): Database::newFromContext(Object(TestSwarmContext))
#3 /var/www/html/testswarm/scripts/install.php(28): TestSwarmContext->getDB()
#4 /var/www/html/testswarm/inc/MaintenanceScript.php(159): DBInstallScript->execute()
#5 /var/www/html/testswarm/scripts/install.php(109): MaintenanceScript->run()
#6 {main}

**Comment by Krinkle** [comment]
@ssomu015 This error indicates that `php-mysqli` is not installed. This is required for PHP to connect with a MySQL server.

<https://packages.ubuntu.com/xenial/php7.0-mysql>

```
apt-get install php7.0-mysql
```

That should do it :)

**Comment by ssomu015** [comment]
> @ssomu015 This error indicates that `php-mysqli` is not installed. This is required for PHP to connect with a MySQL server.
> 
> https://packages.ubuntu.com/xenial/php7.0-mysql
> 
> ```
> apt-get install php7.0-mysql
> ```
> That should do it :)

**Comment by ssomu015** [comment]
> > @ssomu015 This error indicates that `php-mysqli` is not installed. This is required for PHP to connect with a MySQL server.
> > https://packages.ubuntu.com/xenial/php7.0-mysql
> > ```
> > apt-get install php7.0-mysql
> > ```
> > That should do it :)

Its works. Thanks Krinkle for the support.
